### PR TITLE
To do list v1

### PR DESCRIPTION
**Pull request by SulimanJoya**
## Changes
- Created a new repo (
To-Do-List-Project)
- Add linter for HMTL, CSS, and JavaScript 
- Set up the project with webpack
- Add Todo list sections in the index file 
- Add style for different sections  
- Add script for the To Do list 
- Add README file 
- Fixed the linter errors 

## Checklist before requesting a review
- [X] Liner errors 
- [X] GitHub flow
- [X] Documented professionally 
- [X] Followed HTML & CSS best practices 
- [X] Followed JavaScript best practices

### CODE REVIEW

**Comment by SulimanJoya** [comment]
I could not solve this linter error please check my project and tell me the solution 
thank you!

**Review by MeqdamAlqudah — COMMENTED** [review]
Hi @SulimanJoya , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by EricMbouwe — APPROVED** [review]
Hi @SulimanJoya, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Webpack is used to set up the project ✔
- It has an HTML file configured in the Webpack config settings ✔
- has an array of some simple *to do tasks* ✔
- It has a function that iterates over the tasks array and populates the HTML list item element for each task ✔
- Styling ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SulimanJoya** [comment]
I have already done this project before I take leave.

**Review by levy002 — COMMENTED** [review]
## Hello @SulimanJoya 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
