### PR TITLE
To do test

### PR DESCRIPTION
**Pull request by SulimanJoya**
## Changes
- Created a new branch(toDo-test)
- Use jest framework for testing
- Add test for add item
- Add  test for remove item 

## Checklist before requesting a review
- [X] Liner errors 
- [X] GitHub flow
- [X] Documented professionally 
- [X] Followed HTML & CSS best practices 
- [X] Followed JavaScript best practices

### CODE REVIEW

**Comment by SulimanJoya** [comment]
Capture

**Review by amejid — APPROVED** [review]
Hi @SulimanJoya, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- Linter checks passing :heavy_check_mark: 
- Adequate tests :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SulimanJoya** [comment]
I have already done this project before I take leave.

**Review by binhussen — COMMENTED** [review]
Hi @SulimanJoya , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that is pair programming but you did it solo, please do it again with your partner and submit it, because the student success permission will not work for this pr it was only for the previous month 👌

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
